// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgOWlltL7c4A0ZR4rBtFdC203WA0VM_g0',
    appId: '1:486125655456:web:8af46a8d354725c5dd40c5',
    messagingSenderId: '486125655456',
    projectId: 'snapit-1a07d',
    authDomain: 'snapit-1a07d.firebaseapp.com',
    storageBucket: 'snapit-1a07d.appspot.com',
    measurementId: 'G-LT0BXXVS69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnoofPHG5RK4qtNh3TynqiFGFpfOxyYyw',
    appId: '1:486125655456:android:f8b34cb2ef3cd62bdd40c5',
    messagingSenderId: '486125655456',
    projectId: 'snapit-1a07d',
    storageBucket: 'snapit-1a07d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjiOoujU7KSjLOScEj8Rxe28AUHoq08jM',
    appId: '1:486125655456:ios:12318093ced59721dd40c5',
    messagingSenderId: '486125655456',
    projectId: 'snapit-1a07d',
    storageBucket: 'snapit-1a07d.appspot.com',
    iosBundleId: 'com.manyongteam.snapit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjiOoujU7KSjLOScEj8Rxe28AUHoq08jM',
    appId: '1:486125655456:ios:32f419455d829e27dd40c5',
    messagingSenderId: '486125655456',
    projectId: 'snapit-1a07d',
    storageBucket: 'snapit-1a07d.appspot.com',
    iosBundleId: 'com.example.snapit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgOWlltL7c4A0ZR4rBtFdC203WA0VM_g0',
    appId: '1:486125655456:web:2d6a492e798a603cdd40c5',
    messagingSenderId: '486125655456',
    projectId: 'snapit-1a07d',
    authDomain: 'snapit-1a07d.firebaseapp.com',
    storageBucket: 'snapit-1a07d.appspot.com',
    measurementId: 'G-ZQGPTN8K43',
  );
}
